### ISSUE TITLE
关于模型的加载问题

### ISSUE THREAD

**Issue by gjllover** [lh9171338/Unified-Line-Segment-Detection#1]
首先非常感谢作者的工作，我想直接使用预训练模型，但是我的显卡只能支持CUDA10.0，无法安装pytorch1.6，所以您的模型我没法打开。报错如下：
RuntimeError: model/pinhole.pkl is a zip archive (did you mean to use torch.jit.load()?)
解决方案如下：（需要保存成非zip格式）
torch.save(model.state_dict(), model_cp,_use_new_zipfile_serialization=False)
我知道要求稍微有点过分，如果您方便的话，可以更改一下吗？万分感谢！！！

**Comment by lh9171338** [comment]
非zip格式的模型已经上传到网盘中了，链接为https://drive.google.com/drive/folders/1mVbie70cOPixWPBXkzlM75Loq8H0C-Iq?usp=sharing

**Comment by gjllover** [comment]
> 非zip格式的模型已经上传到网盘中了，链接为https://drive.google.com/drive/folders/1mVbie70cOPixWPBXkzlM75Loq8H0C-Iq?usp=sharing

再次感谢您，谢谢！！！
