### ISSUE TITLE
关于鱼眼模型效果

### ISSUE THREAD

**Issue by gjllover** [lh9171338/Unified-Line-Segment-Detection#2]
首先感谢作者的贡献，我尝试运用了您的预训练模型（用于鱼眼图像上的弧线提取），但是并没有取得较好的效果。我观察了一下发现您在项目中给出的测试图像都是512*512，而针孔和球面展开图的测试集虽然有很多都是512*512，但也有其他大小的。因此我疑惑是否鱼眼模型只支持512*512？（因为我拿来测试的图像是1280*1280，甚至2560*2560）
这里给出两张测试的结果，不知道作者是否有好的建议？是否需要设置参数，如何调整？谢谢！
![2](https://user-images.githubusercontent.com/29136914/120133268-62e59880-c1fe-11eb-94f4-2b1d9937e135.png)
![1](https://user-images.githubusercontent.com/29136914/120133277-69741000-c1fe-11eb-912e-0e0ba059ec58.png)

**Comment by lh9171338** [comment]
产生这个问题的一个主要原因是鱼眼图像训练数据集的数据多样性不足（训练用的鱼眼图像主要是通过Wireframe数据集合成的），还不能很好的涵盖不同畸变程度、不同视场角以及不同场景的鱼眼图像，我们正在通过扩增数据集和改进网络来提升模型的泛化能力，我们的训练数据集将尽快发布。同时也建议你自己进行网络训练
